import Head from 'next/head'
import Image from 'next/image'
import { Input } from 'postcss'
import Navbar from '../components/Navbar'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joan Dev| Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/fav.ico"/>
      </Head>
      <Navbar/>
      <Main/>
    </div>
  )
}
